version: '3.9'
services:
  soapservice:
    container_name: listwibuku-soap-service
    build: .
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DATABASE_NAME=soap
      - DATABASE_HOST=host.docker.internal
      - MAIL_HOST=host.docker.internal
      - MAIL_PORT=1025
      - DATABASE_PORT=3307
      - DATABASE_USER=soap
      - DATABASE_PASSWORD=soap
    volumes:
      - .:/usr/src/app
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    container_name: listwibuku-soap-database
    image:
      mysql:8.1
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=soap
      - MYSQL_DATABASE=soap
      - MYSQL_USER=soap
      - MYSQL_PASSWORD=soap
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 10
  mailhog:
    image: mailhog/mailhog
    container_name: 'mailhog'
    ports:
      - "1025:1025"
      - "8025:8025"
volumes:
  db: